testing TravisCI release script (build artefacts, continuous deployment)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -107,52 +107,52 @@ after_failure:
   - 'ls -als dist'
   # - set +e
 # https://docs.travis-ci.com/user/deployment/
-# before_deploy:
-#   - set -e
-#   - export TRAVIS_TAG="latest-$TRAVIS_OS_NAME_"
-#   - node tools/release-github.js
-#   - set +e
-# # - git config --local user.name "danielweck"
-# # - git config --local user.email "daniel.weck@gmail.com"
-# # - git tag -l --format="%(refname)   %(taggerdate)"
-# # - echo $TRAVIS_BRANCH
-# # - export GIT_COMMITTER_DATE="$(git show $TRAVIS_BRANCH --format=%aD | head -1)" && echo $GIT_COMMITTER_DATE
-# # - export GIT_TAG_CURRENT=$(git describe --abbrev=0 --tags) && echo $GIT_TAG_CURRENT
-# # - 'if [[ $GIT_TAG_CURRENT == *-preview ]] ; then
-# #   export TRAVIS_TAG=$GIT_TAG_CURRENT && echo $TRAVIS_TAG ;
-# #   else
-# #   export GIT_TAG_CURRENT_NUM=${GIT_TAG_CURRENT:1} && echo $GIT_TAG_CURRENT_NUM &&
-# #   export GIT_TAG_CURRENT_NUM_LAST_DIGIT=${GIT_TAG_CURRENT_NUM:4} && echo $GIT_TAG_CURRENT_NUM_LAST_DIGIT &&
-# #   export GIT_TAG_CURRENT_NUM_LAST_DIGIT_INC=$((GIT_TAG_CURRENT_NUM_LAST_DIGIT+1)) && echo $GIT_TAG_CURRENT_NUM_LAST_DIGIT_INC &&
-# #   export GIT_TAG_CURRENT_NUM_PREFIX=${GIT_TAG_CURRENT_NUM%.*} && echo $GIT_TAG_CURRENT_NUM_PREFIX &&
-# #   export TRAVIS_TAG="v${GIT_TAG_CURRENT_NUM_PREFIX}.${GIT_TAG_CURRENT_NUM_LAST_DIGIT_INC}-preview" && echo $TRAVIS_TAG &&
-# #   (git tag -a "${TRAVIS_TAG}" $TRAVIS_BRANCH -m "tag ${TRAVIS_TAG}" && echo "tag ok") || echo "tag fail (already exist?)" ;
-# #   fi'
-# # - git tag -l --format="%(refname)   %(taggerdate)"
-# # ((curl -X DELETE --header "Authorization: token ${GH_TOKEN}" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/releases/${GIT_TAG_CURRENT}" && echo "delete release ok") || echo "delete release fail?") &&
-# #  git tag -d $GIT_TAG_CURRENT &&
-# #  git tag -l --format="%(refname)   %(taggerdate)" &&
-# #  git push -q "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" origin :refs/tags/$GIT_TAG_CURRENT > /dev/null 2>&1
-# #  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
-# #  - git push -q --tags "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" origin $TRAVIS_BRANCH > /dev/null 2>&1
-# deploy:
-#   provider: releases
-#   overwrite: true
-#   api_key: $GH_TOKEN
-#   file_glob: true
-#   file:
-#     - "electron-pack/**/*.AppImage"
-#     - "electron-pack/**/*.deb"
-#     - "electron-pack/**/*.msi"
-#     - "electron-pack/**/*.exe"
-#     - "electron-pack/**/*.dmg"
-#     - "!electron-pack/**/elevate*"
-#   skip_cleanup: true
-# # name: "[$TRAVIS_TAG] continuous test build (pre-release)"
-#   prerelease: true
-#   on:
-#     branch: travis
-# #    tags: true
-# # TODO:
-# # https://docs.travis-ci.com/user/build-stages#deploying-to-github-releases
-# # (build stages, shared storage for build artifacts, single deploy (no need to overwrite, no need to deal with concurrent tag access))
+before_deploy:
+  # - set -e
+  - export TRAVIS_TAG="latest-$TRAVIS_OS_NAME_"
+  - node build/release-github.js
+  # - set +e
+# - git config --local user.name "danielweck"
+# - git config --local user.email "daniel.weck@gmail.com"
+# - git tag -l --format="%(refname)   %(taggerdate)"
+# - echo $TRAVIS_BRANCH
+# - export GIT_COMMITTER_DATE="$(git show $TRAVIS_BRANCH --format=%aD | head -1)" && echo $GIT_COMMITTER_DATE
+# - export GIT_TAG_CURRENT=$(git describe --abbrev=0 --tags) && echo $GIT_TAG_CURRENT
+# - 'if [[ $GIT_TAG_CURRENT == *-preview ]] ; then
+#   export TRAVIS_TAG=$GIT_TAG_CURRENT && echo $TRAVIS_TAG ;
+#   else
+#   export GIT_TAG_CURRENT_NUM=${GIT_TAG_CURRENT:1} && echo $GIT_TAG_CURRENT_NUM &&
+#   export GIT_TAG_CURRENT_NUM_LAST_DIGIT=${GIT_TAG_CURRENT_NUM:4} && echo $GIT_TAG_CURRENT_NUM_LAST_DIGIT &&
+#   export GIT_TAG_CURRENT_NUM_LAST_DIGIT_INC=$((GIT_TAG_CURRENT_NUM_LAST_DIGIT+1)) && echo $GIT_TAG_CURRENT_NUM_LAST_DIGIT_INC &&
+#   export GIT_TAG_CURRENT_NUM_PREFIX=${GIT_TAG_CURRENT_NUM%.*} && echo $GIT_TAG_CURRENT_NUM_PREFIX &&
+#   export TRAVIS_TAG="v${GIT_TAG_CURRENT_NUM_PREFIX}.${GIT_TAG_CURRENT_NUM_LAST_DIGIT_INC}-preview" && echo $TRAVIS_TAG &&
+#   (git tag -a "${TRAVIS_TAG}" $TRAVIS_BRANCH -m "tag ${TRAVIS_TAG}" && echo "tag ok") || echo "tag fail (already exist?)" ;
+#   fi'
+# - git tag -l --format="%(refname)   %(taggerdate)"
+# ((curl -X DELETE --header "Authorization: token ${GH_TOKEN}" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/releases/${GIT_TAG_CURRENT}" && echo "delete release ok") || echo "delete release fail?") &&
+#  git tag -d $GIT_TAG_CURRENT &&
+#  git tag -l --format="%(refname)   %(taggerdate)" &&
+#  git push -q "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" origin :refs/tags/$GIT_TAG_CURRENT > /dev/null 2>&1
+#  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
+#  - git push -q --tags "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" origin $TRAVIS_BRANCH > /dev/null 2>&1
+deploy:
+  provider: releases
+  overwrite: true
+  api_key: $GH_TOKEN
+  file_glob: true
+  file:
+    - "dist/**/*.AppImage"
+    - "dist/**/*.deb"
+    - "dist/**/*.msi"
+    - "dist/**/*.exe"
+    - "dist/**/*.dmg"
+    - "!dist/**/elevate*"
+  skip_cleanup: true
+# name: "[$TRAVIS_TAG] continuous test build (pre-release)"
+  prerelease: true
+  on:
+    branch: travis
+#    tags: true
+# TODO:
+# https://docs.travis-ci.com/user/build-stages#deploying-to-github-releases
+# (build stages, shared storage for build artifacts, single deploy (no need to overwrite, no need to deal with concurrent tag access))
